name: Archive

on:
  push:
    branches: [ main ]
    
jobs:
  archive:
    runs-on: macos-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      
    - name: Replace Google AdMob ids
      run: |
          plutil -replace "GADApplicationIdentifier" -string "${{ secrets.GAD_APPLICATION_IDENTIFIER }}" YourTimeManage/Info.plist
          plutil -replace "GADUnitID" -string "${{ secrets.GAD_UNIT_ID }}" YourTimeManage/Info.plist
          plutil -p YourTimeManage/Info.plist

    - name: Decode GoogleService-Info.plist
      run: |
          cd YourTimeManage
          echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST_BASE64 }}" > GoogleService-Info.plist.txt
          base64 --decode GoogleService-Info.plist.txt > GoogleService-Info.plist
          cd ../
          
    - name: Encode provisioning profile
      run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "${{ secrets.PROVISIONING_PROFILE_BASE64 }}" > distribution.mobileprovision.txt
          base64 --decode distribution.mobileprovision.txt > ~/Library/MobileDevice/Provisioning\ Profiles/YourTimeManage_Release.mobileprovision
    
    - name: Import release certificate
      uses: Apple-Actions/import-codesign-certs@v1
      with:
          p12-file-base64: ${{ secrets.CERTIFICATE_BASE64 }}
          p12-password: ${{ secrets.CERTIFICATE_PASSWORD }}

    - name: Archive and create main application target IPA
      run: |
          mkdir ./build
          xcodebuild clean archive -workspace YourTimeManage.xcworkspace -scheme YourTimeManage -configuration Release -destination "platform=iOS Simulator,name=iPhone 12" -archivePath "./build" | xcpretty
          xcodebuild -exportArchive -archivePath "./build" -exportOptionsPlist "YourTimeManage/ExportOptions.plist" | xcpretty
